# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/ADC_interface/ADC_interface.xci
# IP: The module: 'ADC_interface' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/ADC_interface/ADC_interface_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_interface'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/ADC_interface/ADC_interface.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_interface'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/ADC_interface/ADC_interface.xci
# IP: The module: 'ADC_interface' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/ADC_interface/ADC_interface_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_interface'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/ADC_interface/ADC_interface.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_interface'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
