# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.xdc

# IP: ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet

# XDC: ip/clk_pll/clk_pll_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_pll/clk_pll.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_pll/clk_pll_ooc.xdc
