@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jan 17 10:49:52 +0700 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim avg_filter_tb_behav -key {Behavioral:sim_adc_interface:Functional:avg_filter_tb} -tclbatch avg_filter_tb.tcl -log simulate.log"
call xsim  avg_filter_tb_behav -key {Behavioral:sim_adc_interface:Functional:avg_filter_tb} -tclbatch avg_filter_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
