@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Feb 24 18:08:56 +0700 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 1ae869b8bfad457080560d9e6ac0ca58 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L fifo_generator_v13_2_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot slavefifo_verify_tb_behav xil_defaultlib.slavefifo_verify_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 1ae869b8bfad457080560d9e6ac0ca58 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L fifo_generator_v13_2_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot slavefifo_verify_tb_behav xil_defaultlib.slavefifo_verify_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
