# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b.xci
# IP: The module: 'fifo_departure_1024x64b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_departure_1024x64b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_departure_1024x64b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_departure_1024x64b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b.xci
# IP: The module: 'fifo_departure_1024x64b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_departure_1024x64b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_departure_1024x64b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/akrap/Google/AUV/zeabus_hydrophone/FPGA_firmware/zeabus_hydrophone.srcs/sources_1/ip/fifo_departure_1024x64b/fifo_departure_1024x64b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_departure_1024x64b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
