SLStudio.Utils.RemoveHighlighting(get_param('zeabus_hydrophone_fixed_point', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_zeabus_hydrophone_fixed_point', 'handle'));
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample1', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample2', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample2', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample3', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample3', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample4', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample4', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample5', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample5', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample6', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample6', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsmple2', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsmple2', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/numdelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/dendelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/numdelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/dendelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/numdelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/dendelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/numdelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/dendelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/numdelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/dendelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/numdelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/dendelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/numdelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/dendelay_process_section1_tap1', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/numdelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/dendelay_process_section1_tap11', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt/Trigger_FixPt', 1, 1, '');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt/Trigger_FixPt', 1, 1, '');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt', 1, 1, '');
