open_system('zeabus_hydrophone_fixed_point');
open_system('gm_zeabus_hydrophone_fixed_point');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample1', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample2', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample2', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample3', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample3', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample4', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample4', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample5', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample5', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample5', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample6', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample6', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample6', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsample6', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsmple2', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Downsmple2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsmple2', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Downsmple2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/numdelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/numdelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/dendelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/dendelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/numdelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/numdelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/dendelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel1 Filter/dendelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/numdelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/numdelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/dendelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/dendelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/numdelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/numdelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/dendelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel2 Filter/dendelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/numdelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/numdelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/dendelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/dendelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/numdelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/numdelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/dendelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel3 Filter/dendelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/numdelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/numdelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/dendelay_process_section1_tap1', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/dendelay_process_section1_tap1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/numdelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/numdelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/dendelay_process_section1_tap11', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Channel4 Filter/dendelay_process_section1_tap11', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt/Trigger_FixPt', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt/Trigger_FixPt', 1, 1, 'MATLAB blocks and Stateflow charts can be clock-rate pipelined only if they are stateless. For MATLAB blocks, considering removing use of persistent variables');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt/Trigger_FixPt', 'user2');
annotate_port('gm_zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt/Trigger_FixPt', 1, 1, 'MATLAB blocks and Stateflow charts can be clock-rate pipelined only if they are stateless. For MATLAB blocks, considering removing use of persistent variables');
hilite_system('zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt', 'user2');
annotate_port('zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger/Trigger_FixPt', 1, 1, 'MATLAB blocks and Stateflow charts can be clock-rate pipelined only if they are stateless. For MATLAB blocks, considering removing use of persistent variables');
