// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\zeabus_hydrophone_fixed_point\IQ_Demod4.v
// Created: 2020-04-16 11:11:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: IQ_Demod4
// Source Path: zeabus_hydrophone_fixed_point/Hydrophone processing/IQ_Demod4
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 10 ns / 10 ns

module IQ_Demod4
          (Signal_In,
           Sin_Carrier_In,
           Cos_Carrier_In,
           I_Out,
           Q_Out);


  input   signed [17:0] Signal_In;  // sfix18_En17
  input   signed [17:0] Sin_Carrier_In;  // sfix18_En16
  input   signed [17:0] Cos_Carrier_In;  // sfix18_En16
  output  signed [17:0] I_Out;  // sfix18_En17
  output  signed [17:0] Q_Out;  // sfix18_En17


  wire signed [18:0] Unary_Minus_cast;  // sfix19_En17
  wire signed [18:0] Unary_Minus_cast_1;  // sfix19_En17
  wire signed [17:0] Unary_Minus_out1;  // sfix18_En17


  assign Unary_Minus_cast = {Signal_In[17], Signal_In};
  assign Unary_Minus_cast_1 =  - (Unary_Minus_cast);
  assign Unary_Minus_out1 = Unary_Minus_cast_1[17:0];



  assign I_Out = (Cos_Carrier_In == 18'sb000000000000000000 ? Unary_Minus_out1 :
              Signal_In);



  assign Q_Out = (Sin_Carrier_In == 18'sb000000000000000000 ? Unary_Minus_out1 :
              Signal_In);



endmodule  // IQ_Demod4

