// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\zeabus_hydrophone_fixed_point\Median_Filter.v
// Created: 2020-04-16 11:11:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Median_Filter
// Source Path: zeabus_hydrophone_fixed_point/Hydrophone processing/ADC1 Interface/Median Filter
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 10 ns / 10 ns

module Median_Filter
          (clk,
           reset,
           enb,
           u,
           y);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] u;  // sfix18_En17
  output  signed [17:0] y;  // sfix18_En17



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. Median Filter is the original code from the MATLAB function block. Modify this block to update your code or 
  // resolve errors
  // 
  // 2. Median Filter_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to this 
  // block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more.. 


  Median_Filter_FixPt u_Median_Filter_FixPt (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .u(u),  // sfix18_En17
                                             .y(y)  // sfix18_En17
                                             );

endmodule  // Median_Filter

