// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\zeabus_hydrophone_fixed_point\Trigger.v
// Created: 2020-04-16 11:11:01
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Trigger
// Source Path: zeabus_hydrophone_fixed_point/Hydrophone processing/Trigger
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 10 ns / 10 ns

module Trigger
          (clk,
           reset,
           enb_1_64_0,
           i1,
           i2,
           i3,
           i4,
           threshold,
           o1,
           o2,
           o3,
           o4,
           trigged);


  input   clk;
  input   reset;
  input   enb_1_64_0;
  input   signed [17:0] i1;  // sfix18_En17
  input   signed [17:0] i2;  // sfix18_En17
  input   signed [17:0] i3;  // sfix18_En17
  input   signed [17:0] i4;  // sfix18_En17
  input   [15:0] threshold;  // ufix16_En16
  output  signed [17:0] o1;  // sfix18_En17
  output  signed [17:0] o2;  // sfix18_En17
  output  signed [17:0] o3;  // sfix18_En17
  output  signed [17:0] o4;  // sfix18_En17
  output  [7:0] trigged;  // uint8



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. Trigger is the original code from the MATLAB function block. Modify this block to update your code or resolve 
  // errors
  // 
  // 2. Trigger_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to this block 
  // will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more.. 


  Trigger_FixPt u_Trigger_FixPt (.clk(clk),
                                 .reset(reset),
                                 .enb_1_64_0(enb_1_64_0),
                                 .i1(i1),  // sfix18_En17
                                 .i2(i2),  // sfix18_En17
                                 .i3(i3),  // sfix18_En17
                                 .i4(i4),  // sfix18_En17
                                 .threshold(threshold),  // ufix16_En16
                                 .o1(o1),  // sfix18_En17
                                 .o2(o2),  // sfix18_En17
                                 .o3(o3),  // sfix18_En17
                                 .o4(o4),  // sfix18_En17
                                 .trigged(trigged)  // uint8
                                 );

endmodule  // Trigger

